using System.Security.Cryptography;
using apitienda.Data;
using apitienda.Models;
using apitienda.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Serilog;

Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateBootstrapLogger();

try
{
    var builder = WebApplication.CreateBuilder(args);
    builder.Host.UseSerilog((context, services, configuration) => configuration
        .ReadFrom.Configuration(context.Configuration).ReadFrom.Services(services).Enrich.FromLogContext());

    var corsOrigins = builder.Configuration.GetSection("CorsOrigins").Get<string[]>() ?? new[] { "http://localhost:5173", "http://localhost:3000", "http://localhost:8080" };
    builder.Services.AddCors(options => options.AddPolicy("PermitirDominiosEspecificos", policy => policy.WithOrigins(corsOrigins).AllowAnyMethod().AllowAnyHeader()));

    builder.Services.AddDbContext<DataContext>(options => options.UseNpgsql(builder.Configuration.GetConnectionString("UsersDb")));
    builder.Services.AddHttpContextAccessor();
    builder.Services.AddScoped<IAuditoriaService, AuditoriaService>();
    builder.Services.AddScoped<IUsuarioDAO, UsuarioDAO>();
    builder.Services.AddScoped<UsuarioMapper>();
    builder.Services.AddScoped<CreateUserMapper>();
    builder.Services.AddScoped<IUsuarioService, UsuarioService>();
    builder.Services.AddScoped<PasswordResetEmail>();

    builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
    {
        options.TokenValidationParameters = Rs256Validation.Create(builder.Configuration);
    });
    builder.Services.AddAuthorization();
    builder.Services.AddControllers();
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen(options =>
    {
        options.SwaggerDoc("v1", new OpenApiInfo { Title = "Usuarios Service", Version = "v1" });
        options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme { Name = "Authorization", Type = SecuritySchemeType.Http, Scheme = "Bearer", BearerFormat = "JWT", In = ParameterLocation.Header });
        options.AddSecurityRequirement(new OpenApiSecurityRequirement { { new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" } }, Array.Empty<string>() } });
    });

    var app = builder.Build();
    app.UseSerilogRequestLogging();
    app.UseSwagger();
    app.UseSwaggerUI();
    app.UseRouting();
    app.UseCors("PermitirDominiosEspecificos");
    app.UseAuthentication();
    app.UseAuthorization();

    app.MapPost("/internal/users/validate-credentials", async (LoginRequest dto, IUsuarioService service) =>
    {
        var result = await service.ValidateUserAsync(dto.Email, dto.Password);
        if (result is Microsoft.AspNetCore.Mvc.OkObjectResult ok && ok.Value is Usuario user)
        {
            return Results.Ok(new ValidatedUserResponse(user.id, user.email ?? string.Empty));
        }

        return Results.Unauthorized();
    }).AllowAnonymous();

    app.MapControllers();

    await DatabaseStartup.EnsureCreatedAsync<DataContext>(app.Services, app.Logger);
    await DatabaseStartup.EnsureAuditTableAsync<DataContext>(app.Services, app.Logger);

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Usuarios Service fallo al iniciar.");
}
finally
{
    Log.CloseAndFlush();
}

public static class DatabaseStartup
{
    public static async Task EnsureCreatedAsync<TContext>(
        IServiceProvider services,
        Microsoft.Extensions.Logging.ILogger logger)
        where TContext : DbContext
    {
        for (var attempt = 1; attempt <= 10; attempt++)
        {
            try
            {
                using var scope = services.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<TContext>();
                await db.Database.EnsureCreatedAsync();
                return;
            }
            catch (Exception ex) when (attempt < 10)
            {
                logger.LogWarning(ex, "La base de datos aun no esta lista. Reintento {Attempt}/10.", attempt);
                await Task.Delay(TimeSpan.FromSeconds(3));
            }
        }
    }

    public static async Task EnsureAuditTableAsync<TContext>(IServiceProvider services, Microsoft.Extensions.Logging.ILogger logger)
        where TContext : DbContext
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<TContext>();
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS auditoria (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Usuario" text NOT NULL,
                "Accion" text NOT NULL,
                "Tabla" text NOT NULL,
                "RegistroId" text NULL,
                "Detalle" text NULL,
                "Fecha" timestamp with time zone NOT NULL,
                "IpAddress" text NULL
            );
            """);
        logger.LogInformation("Tabla de auditoria verificada.");
    }
}

public record LoginRequest(string Email, string Password);
public record ValidatedUserResponse(Guid Id, string Email);

public static class Rs256Validation
{
    public static TokenValidationParameters Create(IConfiguration configuration)
    {
        var rsa = RSA.Create();
        rsa.ImportFromPem(File.ReadAllText(configuration["Jwt:PublicKeyPath"]!));
        return new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = configuration["Jwt:Issuer"],
            ValidAudience = configuration["Jwt:Audience"],
            IssuerSigningKey = new RsaSecurityKey(rsa),
            ClockSkew = TimeSpan.Zero
        };
    }
}
