using System.Security.Cryptography;
using apitienda.Data;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using productos.Data;
using Serilog;

Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateBootstrapLogger();

try
{
    var builder = WebApplication.CreateBuilder(args);
    builder.Host.UseSerilog((context, services, configuration) => configuration
        .ReadFrom.Configuration(context.Configuration).ReadFrom.Services(services)
        .Enrich.FromLogContext());

    var corsOrigins = builder.Configuration.GetSection("CorsOrigins").Get<string[]>() ?? new[] { "http://localhost:5173", "http://localhost:3000", "http://localhost:8080" };
    builder.Services.AddCors(options => options.AddPolicy("PermitirDominiosEspecificos", policy => policy.WithOrigins(corsOrigins).AllowAnyMethod().AllowAnyHeader()));

    builder.Services.AddDbContext<DataContextProduct>(options => options.UseNpgsql(builder.Configuration.GetConnectionString("ProductsDb")));
    builder.Services.AddDbContext<DataContext>(options => options.UseNpgsql(builder.Configuration.GetConnectionString("ProductsDb")));
    builder.Services.AddHttpContextAccessor();
    builder.Services.AddScoped<IProductDAO, ProductDAO>();
    builder.Services.AddScoped<IProductService, ProductService>();
    builder.Services.AddScoped<ProductMapper>();
    builder.Services.AddScoped<CreateProductMapper>();

    builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
    {
        options.TokenValidationParameters = Rs256Validation.Create(builder.Configuration);
    });
    builder.Services.AddAuthorization();
    builder.Services.AddControllers();
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen(options =>
    {
        options.SwaggerDoc("v1", new OpenApiInfo { Title = "Productos Service", Version = "v1" });
        options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme { Name = "Authorization", Type = SecuritySchemeType.Http, Scheme = "Bearer", BearerFormat = "JWT", In = ParameterLocation.Header });
        options.AddSecurityRequirement(new OpenApiSecurityRequirement { { new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" } }, Array.Empty<string>() } });
    });

    var app = builder.Build();
    app.UseSerilogRequestLogging();
    app.UseSwagger();
    app.UseSwaggerUI();
    app.UseRouting();
    app.UseCors("PermitirDominiosEspecificos");
    app.UseAuthentication();
    app.UseAuthorization();
    app.MapControllers();

    await DatabaseStartup.EnsureCreatedAsync<DataContextProduct>(app.Services, app.Logger);
    await DatabaseStartup.EnsureCreatedAsync<DataContext>(app.Services, app.Logger);
    await DatabaseStartup.EnsureAuditTableAsync<DataContext>(app.Services, app.Logger);

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Productos Service fallo al iniciar.");
}
finally
{
    Log.CloseAndFlush();
}

public static class DatabaseStartup
{
    public static async Task EnsureCreatedAsync<TContext>(
        IServiceProvider services,
        Microsoft.Extensions.Logging.ILogger logger)
        where TContext : DbContext
    {
        for (var attempt = 1; attempt <= 10; attempt++)
        {
            try
            {
                using var scope = services.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<TContext>();
                await db.Database.EnsureCreatedAsync();
                return;
            }
            catch (Exception ex) when (attempt < 10)
            {
                logger.LogWarning(ex, "La base de datos aun no esta lista. Reintento {Attempt}/10.", attempt);
                await Task.Delay(TimeSpan.FromSeconds(3));
            }
        }
    }

    public static async Task EnsureAuditTableAsync<TContext>(IServiceProvider services, Microsoft.Extensions.Logging.ILogger logger)
        where TContext : DbContext
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<TContext>();
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS auditoria (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Usuario" text NOT NULL,
                "Accion" text NOT NULL,
                "Tabla" text NOT NULL,
                "RegistroId" text NULL,
                "Detalle" text NULL,
                "Fecha" timestamp with time zone NOT NULL,
                "IpAddress" text NULL
            );
            """);
        logger.LogInformation("Tabla de auditoria verificada.");
    }
}

public static class Rs256Validation
{
    public static TokenValidationParameters Create(IConfiguration configuration)
    {
        var rsa = RSA.Create();
        rsa.ImportFromPem(File.ReadAllText(configuration["Jwt:PublicKeyPath"]!));
        return new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = configuration["Jwt:Issuer"],
            ValidAudience = configuration["Jwt:Audience"],
            IssuerSigningKey = new RsaSecurityKey(rsa),
            ClockSkew = TimeSpan.Zero
        };
    }
}
