using apitienda.Data;
using apitienda.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using Serilog;

Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateBootstrapLogger();

try
{
    var builder = WebApplication.CreateBuilder(args);
    builder.Host.UseSerilog((context, services, configuration) => configuration
        .ReadFrom.Configuration(context.Configuration).ReadFrom.Services(services).Enrich.FromLogContext());

    var corsOrigins = builder.Configuration.GetSection("CorsOrigins").Get<string[]>() ?? new[] { "http://localhost:5173", "http://localhost:3000", "http://localhost:8080" };
    builder.Services.AddCors(options => options.AddPolicy("PermitirDominiosEspecificos", policy => policy.WithOrigins(corsOrigins).AllowAnyMethod().AllowAnyHeader()));

    builder.Services.AddDbContext<AuthDbContext>(options => options.UseNpgsql(builder.Configuration.GetConnectionString("AuthDb")));
    builder.Services.AddHttpContextAccessor();
    builder.Services.AddScoped<IAuditoriaService, AuditoriaService>();
    builder.Services.AddScoped<IJwtService, JwtService>();
    builder.Services.AddScoped<IAuthService, AuthService>();
    builder.Services.AddHttpClient("UsersService", client =>
    {
        client.BaseAddress = new Uri(builder.Configuration["Services:Users"]!);
    });
    builder.Services.AddControllers();
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen(options =>
    {
        options.SwaggerDoc("v1", new OpenApiInfo { Title = "Autenticacion Service", Version = "v1" });
    });

    var app = builder.Build();
    app.UseSerilogRequestLogging();
    app.UseSwagger();
    app.UseSwaggerUI();
    app.UseRouting();
    app.UseCors("PermitirDominiosEspecificos");
    app.MapControllers();

    await DatabaseStartup.EnsureCreatedAsync<AuthDbContext>(app.Services, app.Logger);
    await DatabaseStartup.EnsureAuditTableAsync<AuthDbContext>(app.Services, app.Logger);

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Auth Service fallo al iniciar.");
}
finally
{
    Log.CloseAndFlush();
}

public static class DatabaseStartup
{
    public static async Task EnsureCreatedAsync<TContext>(
        IServiceProvider services,
        Microsoft.Extensions.Logging.ILogger logger)
        where TContext : DbContext
    {
        for (var attempt = 1; attempt <= 10; attempt++)
        {
            try
            {
                using var scope = services.CreateScope();
                var db = scope.ServiceProvider.GetRequiredService<TContext>();
                await db.Database.EnsureCreatedAsync();
                return;
            }
            catch (Exception ex) when (attempt < 10)
            {
                logger.LogWarning(ex, "La base de datos aun no esta lista. Reintento {Attempt}/10.", attempt);
                await Task.Delay(TimeSpan.FromSeconds(3));
            }
        }
    }

    public static async Task EnsureAuditTableAsync<TContext>(IServiceProvider services, Microsoft.Extensions.Logging.ILogger logger)
        where TContext : DbContext
    {
        using var scope = services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<TContext>();
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS auditoria (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Usuario" text NOT NULL,
                "Accion" text NOT NULL,
                "Tabla" text NOT NULL,
                "RegistroId" text NULL,
                "Detalle" text NULL,
                "Fecha" timestamp with time zone NOT NULL,
                "IpAddress" text NULL
            );
            """);
        logger.LogInformation("Tabla de auditoria verificada.");
    }
}
